name: corridasegura
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  google_fonts: ^5.1.0
  firebase_auth: ^4.9.0
  liquid_swipe: ^3.1.0
  flutter_native_splash: ^2.3.2
  get: ^4.6.5
  brasil_fields: ^1.14.0
  email_validator: ^2.1.17
  image_picker: ^1.0.4
  permission_handler: ^10.4.3
  cloud_firestore: ^4.9.1
  google_maps_flutter: ^2.5.0
  mask_text_input_formatter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  flutter_svg: ^2.0.7
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/images/corrida_segura_logo.png
  image_dark: assets/images/corrida_segura_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
